FROM node:20-alpine

# Enable pnpm via Corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY dist ./dist
COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install --prod

EXPOSE 4000
CMD ["node", "dist/main"]
