apiVersion: v1
kind: Pod
metadata:
  name: jenkins-backend-agent
spec:
  serviceAccountName: jenkins-agent
  containers:
    - name: node
      image: node:20-alpine
      command: ['sleep']
      args: ['99d']
      tty: true

    - name: dispatchai-jenkins-agent
      image: 893774231297.dkr.ecr.ap-southeast-2.amazonaws.com/dispatchai-jenkins-agent:lawrence
      imagePullPolicy: Always
      command: ['sleep']
      args: ['99d']
      tty: true
      env:
        - name: AWS_REGION
          value: "ap-southeast-2"
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock

    - name: buildkitd
      image: moby/buildkit:v0.12.4
      command: ["buildkitd"]
      args: ["--addr=tcp://0.0.0.0:1234"]
      ports:
        - containerPort: 1234
          name: buildkit
      securityContext:
        privileged: true

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
